export interface TravelDestination {
  id: number;
  name: string;
  description: string;
  location: string;
  image: string;
  tags: string[];
  rating: number;
  price: number;
}

export const travelDestinations: TravelDestination[] = [
  {
    id: 1,
    name: "활기찬 해양도시, 부산 완전 정복",
    description: "해운대 해변, 자갈치 시장, 감천문화마을 등 부산의 모든 것",
    location: "부산",
    image: "/images/id_001.jpg",
    tags: ["바다", "맛집", "쇼핑", "역사투어", "아쿠아리움"],
    rating: 4.7,
    price: 350000,
  },
  {
    id: 2,
    name: "로맨틱한 밤바다, 여수 낭만 여행",
    description: "돌산대교 야경, 해상 케이블카, 오동도 동백꽃",
    location: "여수",
    image: "/images/id_002.jpg",
    tags: ["바다", "크루즈", "맛집", "아쿠아리움"],
    rating: 4.5,
    price: 420000,
  },
  {
    id: 3,
    name: "예술과 역사의 섬, 통영",
    description: "동피랑 벽화마일, 이순신 공원, 한려수도 조망 케이블카",
    location: "통영",
    image: "/images/id_003.jpg",
    tags: ["바다", "역사투어", "맛집"],
    rating: 4.3,
    price: 280000,
  },
  {
    id: 4,
    name: "산과 계곡의 조화, 정선 힐링 캠프",
    description: "정선 5일장, 화암동굴, 아라리촌, 레일바이크 체험",
    location: "정선",
    image: "/images/id_004.jpg",
    tags: ["등산", "템플", "농촌체험", "캠핑", "봉사"],
    rating: 4.8,
    price: 250000,
  },
  {
    id: 5,
    name: "지붕 없는 박물관, 강화도 역사 기행",
    description: "고인돌 유적, 전등사, 초지진, 평화전망대",
    location: "강화도",
    image: "/images/id_005.jpg",
    tags: ["템플", "역사투어", "바다", "박물관"],
    rating: 4.4,
    price: 180000,
  },
  {
    id: 6,
    name: "천년고도, 경주 신라 역사 탐방",
    description: "불국사, 석굴암, 첨성대, 동궁과 월지",
    location: "경주",
    image: "/images/id_006.jpg",
    tags: ["역사투어", "맛집", "박물관", "템플"],
    rating: 4.9,
    price: 320000,
  },
  {
    id: 7,
    name: "환상의 섬, 제주도 완전 정복",
    description: "한라산 등반, 성산일출봉, 흑돼지 맛집, 에메랄드빛 해변",
    location: "제주",
    image: "/images/id_007.jpg",
    tags: ["바다", "맛집", "등산", "농촌체험", "승마", "골프"],
    rating: 4.9,
    price: 750000,
  },
  {
    id: 8,
    name: "설악과 동해의 만남, 속초",
    description: "설악산 국립공원, 속초 해수욕장, 아바이마을",
    location: "속초",
    image: "/images/id_008.jpg",
    tags: ["바다", "맛집", "낚시", "등산"],
    rating: 4.6,
    price: 380000,
  },
  {
    id: 9,
    name: "호반의 도시, 춘천 낭만 여행",
    description: "남이섬, 소양강 스카이워크, 닭갈비 골목",
    location: "춘천",
    image: "/images/id_009.jpg",
    tags: ["맛집", "등산", "쇼핑"],
    rating: 4.3,
    price: 290000,
  },
  {
    id: 10,
    name: "겨울 스포츠의 성지, 평창",
    description: "스키 리조트, 양떼목장, 오대산 국립공원",
    location: "평창",
    image: "/images/id_010.jpg",
    tags: ["스키", "등산", "캠핑", "골프"],
    rating: 4.8,
    price: 880000,
  },
  {
    id: 11,
    name: "짜릿한 즐거움, 용인 테마파크",
    description: "에버랜드, 한국민속촌, 캐리비안 베이",
    location: "용인",
    image: "/images/id_011.jpg",
    tags: ["테마파크", "맛집", "쇼핑"],
    rating: 4.7,
    price: 550000,
  },
  {
    id: 12,
    name: "따뜻한 휴식, 아산 온천 여행",
    description: "온양온천, 현충사, 외암민속마을",
    location: "아산",
    image: "/images/id_012.jpg",
    tags: ["온천", "역사투어", "템플"],
    rating: 4.5,
    price: 220000,
  },
  {
    id: 13,
    name: "머드와 축제의 도시, 보령",
    description: "대천 해수욕장, 머드 축제, 스카이바이크",
    location: "보령",
    image: "/images/id_013.jpg",
    tags: ["바다", "페스티벌", "낚시"],
    rating: 4.2,
    price: 190000,
  },
  {
    id: 14,
    name: "수도 서울, 다이나믹 시티 투어",
    description: "경복궁, 명동 쇼핑, 홍대 맛집, 롯데월드",
    location: "서울",
    image: "/images/id_014.jpg",
    tags: ["쇼핑", "맛집", "박물관", "베이킹", "테마파크", "역사투어"],
    rating: 4.8,
    price: 950000,
  },
];